query Query($userId: Float!) {
  getUrlsByUserId(userId: $userId) {
    email
    id
    responses {
      created_at
      id
      latency
      response_status
    }
    role
    userToUrls {
      frequency
    }
    username
  }
}
