query getUrlById($urlId: Float!) {
  getUrlById(urlId: $urlId) {
    latency_treshold
    url {
      id
      url
      created_at
      frequency
      responses {
        id
        response_status
        latency
        created_at
      }
    }
  }
}
